# Generated by Django 5.2.7 on 2025-11-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casospacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='texto',
        ),
    ]
